enum IntoleranceType: String {
    case notIntolerance = ""
    case dairy = "Dairy"
    case egg = "Egg"
    case gluten = "Gluten"
    case grain = "Grain"
    case peanut = "Peanut"
    case seafood = "Seafood"
    case sesame = "Sesame"
    case shellfish = "Shellfish"
    case soy = "Soy"
    case sulfite = "Sulfite"
    case treeNut = "Tree nut"
    case wheat = "Wheat"
}
