# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'Kitchen Buddy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kitchen Buddy
	pod 'SnapKit', '~> 5.0.0'
	pod 'SwiftLint', '~> 0.46.2'
	pod 'Alamofire'
	pod 'Moya', '~> 15.0'
	pod 'Swinject'
	pod 'Kingfisher', '~> 7.0'
	pod 'SwiftGen'
end
